<?xml version="1.0"?>
<robot name="scout_v2" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ======================= -->
  <!-- Xacro Arguments        -->
  <!-- ======================= -->
  <xacro:arg name="robot_namespace" default="/" />

  <!-- ======================= -->
  <!-- Constants / Properties  -->
  <!-- ======================= -->
  <xacro:property name="M_PI" value="3.14159"/>
  <xacro:property name="wheelbase" value="0.498"/>
  <xacro:property name="track" value="0.58306"/>
  <xacro:property name="wheel_vertical_offset" value="-0.0702"/>
  <xacro:property name="wheel_length" value="0.11653"/>
  <xacro:property name="wheel_radius" value="0.16459"/>

  <xacro:property name="base_x_size" value="0.925"/>
  <xacro:property name="base_y_size" value="0.380"/>
  <xacro:property name="base_z_size" value="0.210"/>

  <!-- ======================= -->
  <!-- Include Gazebo-safe Macros -->
  <!-- ======================= -->
  <xacro:include filename="$(find scout_gazebo)/gazebo_urdf/scout_wheel_type1_gazebo.xacro"/>
  <xacro:include filename="$(find scout_gazebo)/gazebo_urdf/scout_wheel_type2_gazebo.xacro"/>
  <xacro:include filename="$(find scout_gazebo)/gazebo_urdf/scout_transmissions.xacro"/>
  <xacro:include filename="$(find scout_description)/urdf/scout_xarm_base.xacro"/>

  <!-- ======================= -->
  <!-- Base / XArm Base Macro  -->
  <!-- ======================= -->
  <xacro:scout_xarm_base/>

  <joint name="box_link_joint" type="fixed">
    <parent link="base_link"/>
    <child link="box_link"/>
    <origin xyz="0 0 0.10" rpy="0 0 0"/>
  </joint>

  <!-- ======================= -->
  <!-- Base Link Definition    -->
  <!-- ======================= -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find scout_description)/meshes/base_link.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.008" rpy="0 0 0"/>
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
      </geometry>
    </collision>
    <collision>
      <origin xyz="0 0 ${base_z_size/6}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_x_size/6} ${base_y_size*1.65} ${base_z_size/3}"/>
      </geometry>
    </collision>
  </link>

  <!-- Inertial Link -->
  <link name="inertial_link">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="40"/>
      <inertia ixx="2.288641" ixy="0" ixz="0"
               iyy="5.103976" iyz="0" izz="3.431465"/>
    </inertial>
  </link>

  <joint name="inertial_joint" type="fixed">
    <parent link="base_link"/>
    <child link="inertial_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- ======================= -->
  <!-- Wheels                  -->
  <!-- ======================= -->
  <xacro:scout_wheel_type1 wheel_prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14159 0 0"/>
  </xacro:scout_wheel_type1>

  <xacro:scout_wheel_type2 wheel_prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
  </xacro:scout_wheel_type2>

  <xacro:scout_wheel_type1 wheel_prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
  </xacro:scout_wheel_type1>

  <xacro:scout_wheel_type2 wheel_prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14159 0 0"/>
  </xacro:scout_wheel_type2>

  <!-- ======================= -->
  <!-- Transmissions           -->
  <!-- ======================= -->
  <xacro:scout_wheel_transmission wheel_prefix="front_left"/>
  <xacro:scout_wheel_transmission wheel_prefix="front_right"/>
  <xacro:scout_wheel_transmission wheel_prefix="rear_left"/>
  <xacro:scout_wheel_transmission wheel_prefix="rear_right"/>

  <!-- ======================= -->
  <!-- Gazebo Skid-Steer Plugin -->
  <!-- ======================= -->
  <!--
  <gazebo>
    <plugin name="gazebo_ros_skid_steer" filename="libgazebo_ros_skid_steer.so">
      <ros2_namespace>/</ros2_namespace>
      <left_joint>front_left_wheel_joint</left_joint>
      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>front_right_wheel_joint</right_joint>
      <right_joint>rear_right_wheel_joint</right_joint>
      <wheel_separation>${track}</wheel_separation>
      <wheel_diameter>${2*wheel_radius}</wheel_diameter>
      <update_rate>100</update_rate>
      <command_topic>cmd_vel</command_topic>
      <odometry_topic>odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>
    </plugin>
  </gazebo>
  -->

  <!-- ======================= -->
<!-- Gazebo Differential Drive Plugin -->
<!-- ======================= -->
<gazebo>
  <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
    <ros>
      <namespace>/</namespace>
      <remapping>cmd_vel:=cmd_vel</remapping>
      <remapping>odom:=odom</remapping>
    </ros>
    <update_rate>100.0</update_rate>

    <!-- Define the wheels -->
    <num_wheel_pairs>2</num_wheel_pairs>
    <left_joint>front_left_wheel_joint</left_joint>
    <left_joint>rear_left_wheel_joint</left_joint>
    <right_joint>front_right_wheel_joint</right_joint>
    <right_joint>rear_right_wheel_joint</right_joint>

    <wheel_separation>${track}</wheel_separation>
    <wheel_radius>${wheel_radius}</wheel_radius>

    <publish_odom>true</publish_odom>
    <odometry_frame>odom</odometry_frame>
    <robot_base_frame>base_link</robot_base_frame>
  </plugin>
</gazebo>


</robot>
