<?xml version="1.0"?>
<robot name="scout_v2" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ======================= -->
  <!-- Xacro Arguments        -->
  <!-- ======================= -->
  <xacro:arg name="robot_namespace" default="/" />

  <!-- ======================= -->
  <!-- Constants / Properties  -->
  <!-- ======================= -->
  <xacro:property name="M_PI" value="3.14159"/>
  <xacro:property name="wheelbase" value="0.498"/>
  <xacro:property name="track" value="0.58306"/>
  <xacro:property name="wheel_vertical_offset" value="-0.0702"/>
  <xacro:property name="wheel_length" value="0.11653"/>
  <xacro:property name="wheel_radius" value="0.16459"/>

  <!-- Base dimensions -->
  <xacro:property name="base_x_size" value="0.925"/>
  <xacro:property name="base_y_size" value="0.380"/>
  <xacro:property name="base_z_size" value="0.210"/>

  <!-- ======================= -->
  <!-- Include Macros          -->
  <!-- ======================= -->
  <xacro:include filename="$(find scout_description)/urdf/scout_wheel_type1.xacro"/>
  <xacro:include filename="$(find scout_description)/urdf/scout_wheel_type2.xacro"/>
  <xacro:include filename="$(find scout_description)/urdf/scout_xarm_base.xacro"/>

  <!-- ======================= -->
  <!-- Base / XArm Base Macro  -->
  <!-- ======================= -->
  <!-- Use the xarm base macro which defines box_link + laser + display -->
  <xacro:scout_xarm_base/>

  <!-- Attach xarm base on top of base_link -->
  <joint name="box_link_joint" type="fixed">
    <parent link="base_link"/>
    <child link="box_link"/>
    <origin xyz="0 0 0.10" rpy="0 0 0"/>
  </joint>

  <!-- ======================= -->
  <!-- Base Link Definition    -->
  <!-- ======================= -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://scout_description/meshes/base_link.dae"/>
      </geometry>
    </visual>

    <!-- Primary collision box -->
    <collision>
      <origin xyz="0 0 0.008" rpy="0 0 0"/>
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
      </geometry>
    </collision>

    <!-- Secondary collision (support / clearance) -->
    <collision>
      <origin xyz="0 0 ${base_z_size/6}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_x_size/6} ${base_y_size*1.65} ${base_z_size/3}"/>
      </geometry>
    </collision>
  </link>

  <!-- ======================= -->
  <!-- Inertial Link           -->
  <!-- ======================= -->
  <link name="inertial_link">
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="40"/>
      <inertia
        ixx="2.288641"
        ixy="0"
        ixz="0"
        iyy="5.103976"
        iyz="0"
        izz="3.431465"/>
    </inertial>
  </link>

  <joint name="inertial_joint" type="fixed">
    <parent link="base_link"/>
    <child link="inertial_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- ======================= -->
  <!-- Wheels                  -->
  <!-- ======================= -->
  <!-- Front Right -->
  <xacro:scout_wheel_type1 wheel_prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0"/>
  </xacro:scout_wheel_type1>

  <!-- Front Left -->
  <xacro:scout_wheel_type2 wheel_prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
  </xacro:scout_wheel_type2>

  <!-- Rear Left -->
  <xacro:scout_wheel_type1 wheel_prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0"/>
  </xacro:scout_wheel_type1>

  <!-- Rear Right -->
  <xacro:scout_wheel_type2 wheel_prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="3.14 0 0"/>
  </xacro:scout_wheel_type2>

 
<!-- ======================= -->
<!-- Gazebo Plugins          -->
<!-- ======================= -->
<!--<xacro:include filename="$(find scout_description)/urdf/scout_v2.gazebo"/>-->


</robot>
